# Generated by Django 6.0.6 on 2026-07-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='reward_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
